site_name: PDFResource
docs_dir: core/components/pdfresource/docs/mkdocs
site_dir: _build/site

repo_name: 'Jako/PDFResource'
repo_url: https://github.com/Jako/PDFResource

copyright: '&copy; 2015–2017 <a href="https://treehillstudio.com">Treehill Studio</a>'

pages:
- Description: 'index.md'
- Installation: 'installation.md'
- Usage: 'usage.md'
- Donate: 'donate.md'

extra:
  font:
    text: 'Dosis'
    heading: 'Ubuntu'

piwik_analytics:
  site_id: 18
  piwik_url: 'https://piwik.partout.info/'

theme: 'material'
theme_dir: '/Users/jako/Documents/MODx/MkDocs Material/material'

markdown_extensions:
  - footnotes
  - tables
  - admonition
  - meta
  - toc(permalink=true)
