site_name: PDFresource
docs_dir: core/components/pdfresource/docs
site_dir: _build/site

repo_url: https://github.com/Jako/PDFresource

pages:
- Home: 'index.md'
- Installation: 'installation.md'
- Usage: 'usage.md'
- Donate: 'donate.md'

theme: flatly

markdown_extensions:
    - footnotes
    - tables