site_name: PDFResource
docs_dir: core/components/pdfresource/docs/mkdocs
site_dir: _build/site

repo_url: https://github.com/Jako/PDFResource

pages:
- Home: 'index.md'
- Installation: 'installation.md'
- Usage: 'usage.md'
- Donate: 'donate.md'

theme: flatly

markdown_extensions:
    - footnotes
    - tables